define(['./auth/userservice',
        './auth/permissionservice',
        './auth/roleservice',
        './auth/authservice',
        './auth/authinterceptor',
       // './socketservice',
        './indexedDbService',
        './drawService',
        './recycleService',
        './accessentryservice'],function(){});