define(['./auth/userservice',
    './auth/permissionservice',
    './auth/roleservice',
    './auth/authservice',
    './auth/authinterceptor',
   // './socketservice',
    './indexedDbService',
    './opsupport/baseOpSupportService',
    './opsupport/drawService',
    './opsupport/recycleService',
    './accessentryservice',
    './opsupport/oproomservice',
    './opsupport/syncuserservice',
    './external/hisservice'
],function(){});